/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package leaverecords.gui;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import staffdatamodel.StaffList;
import staffdatamodel.StaffMember;

/**
 *
 * A form used to edit a staff members details.
 * 
 * @author Adam Stevenson
 */
public class EditStaffMember extends javax.swing.JFrame {

    private StaffList staffList;
    int selectedStaffMember;

    /**
     * Creates new form EditStaffMember. This is responsible for 
     * Importing the staff members details, for either alteration
     * or deletion from the staff list. 
     */
    public EditStaffMember() {   
        initComponents();
        backgroundPanel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditCancel = new javax.swing.JButton();
        btnEditStaff = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        btnEditStaffHelp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblSurname = new javax.swing.JLabel();
        txtEditSurname = new javax.swing.JTextField();
        txtEditDepartment = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtEditForename = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(930, 0, 0, 0));
        setResizable(false);

        btnEditCancel.setText("Close");
        btnEditCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCancelMouseClicked(evt);
            }
        });

        btnEditStaff.setText("Edit");
        btnEditStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditStaffMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Edit Staff Member Details");

        btnEditStaffHelp.setText("Help");
        btnEditStaffHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditStaffHelpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditStaffHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditStaffHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lblHeading))
                .addGap(4, 4, 4))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSurname.setText("Surname:");

        txtEditSurname.setToolTipText("");

        lblFirstName.setText("First Name:");

        lblDepartment.setText("Department:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSurname)
                    .addComponent(lblFirstName)
                    .addComponent(lblDepartment))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEditForename)
                    .addComponent(txtEditSurname)
                    .addComponent(txtEditDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditForename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSurname))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartment))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnEditCancelMouseClicked

    private void btnEditStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditStaffMouseClicked
        editStaffMember();
    }//GEN-LAST:event_btnEditStaffMouseClicked

    private void btnEditStaffHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditStaffHelpMouseClicked
         JOptionPane.showMessageDialog(this,
            "<html>Editing a staff member:  "
                 + "<br><br>Simply replace a text field with another value."
                 + "<br><br> Note: It is possible to leave the forename and surname blank."
                 + "<br> but the department is required.</html> \"",
            "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditStaffHelpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStaffMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStaffMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStaffMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStaffMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStaffMember().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditCancel;
    private javax.swing.JButton btnEditStaff;
    private javax.swing.JButton btnEditStaffHelp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JTextField txtEditDepartment;
    private javax.swing.JTextField txtEditForename;
    private javax.swing.JTextField txtEditSurname;
    // End of variables declaration//GEN-END:variables

   /**
    * Creates the background graphics
    */
    public void backgroundPanel(){    
    
        setTitle("Edit Staff Member");
        
        setLayout(new BorderLayout());
        JLabel lblBackground = new JLabel(new ImageIcon("images/Background.JPG"));
        
        add (lblBackground);
        lblBackground.setLayout(new FlowLayout());
    }
       
   /**
    * Initialise the staff member (provides the stafflist and the index of the
    * selected staff member).
    * Then sets the text fields.
    * 
    * @param staffList = the carried across arraylist pertaining to staff members
    * @param selectedStaffMember = the index of the staff member
    * 
    */
    public void setStaffList(StaffList objTarget, int selectedIndex){
    
            staffList = objTarget;
            selectedStaffMember = selectedIndex;

            txtEditForename.setText(staffList.getStaffAt(selectedStaffMember).getForename());
            txtEditSurname.setText(staffList.getStaffAt(selectedStaffMember).getSurname());
            txtEditDepartment.setText(staffList.getStaffAt(selectedStaffMember).getDept());
    }
 
   /**
    * Edit the staff members details. The staff members index is provided
    * and used as an index to alter the members details; staff members are contained
    * within the arraylist staffList.
    * 
    * @param staffToChange = the staff member to change
    * 
    * @throws IllegalArgumentException
    */
    private void editStaffMember(){
        
        if (this.isEditable()){
        
            StaffMember staffToChange;
            staffToChange = staffList.getStaffAt(selectedStaffMember);
            
            
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to edit the staff member: "
                    + staffToChange.getFullName(),
                    "Confirm change", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION)
            {
                
            try{
                
                if (txtEditForename.getText().length() == 0
                        && txtEditSurname.getText().length() == 0)
                {
                    txtEditForename.setText("UNKNOWN");
                    txtEditSurname.setText("UNKNOWN");
                }
                
                staffToChange.setForename(txtEditForename.getText());
                staffToChange.setSurname(txtEditSurname.getText());
                staffToChange.setDept(txtEditDepartment.getText());
                
                JOptionPane.showMessageDialog(this, 
                "Staff member has been successfully edited", 
                "Staff Member changed successfully", JOptionPane.INFORMATION_MESSAGE);
                staffList.notifyObservers();
                this.dispose();
                
                }  
            catch (IllegalArgumentException ex)
                {
                   JOptionPane.showMessageDialog(this, ex.getMessage(),
                           "Invalid Data!", JOptionPane.ERROR_MESSAGE);
                }
            }
        } 
    }
    
   /**
    * Before the staff members details are edited. This method checks
    * that all the textboxes are filled with valid data.
    * 
    */
    private Boolean isEditable()
    {
        Boolean blnValid = false;
        try
        {
            // second constructor
            if (txtEditForename.getText().length() > 0 && txtEditSurname.getText().length() > 0
                    && txtEditDepartment.getText().length() > 0)
            {
                blnValid = true;
            } 
            // default constructor
            else if (txtEditForename.getText().length() == 0 && txtEditSurname.getText().length() == 0
                    && txtEditDepartment.getText().length() > 0)
            {
                blnValid = true;    
            }
            else
            {
                throw new IllegalArgumentException("The staff member "
                        + "has invalid data. Please click on the help button"
                        + "for more information");
            }
        } catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "The provided data is invalid", 
                    "Error reading data", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), 
                    "Invalid Data!", JOptionPane.ERROR_MESSAGE);
        }
        return blnValid;
    }
}
